[workspace]
members = [
	"apps/desktop/src-tauri",
	"apps/server",
	"apps/sdtunnel",
	"apps/sdtunnel/utils",
	"core",
	"core/prisma",
	"core/derive",
	"core/p2p"
]

[patch.crates-io]
rspc = { git = "https://github.com/oscartbeaumont/rspc.git" } # TODO: Move back to crates.io release when custom bindings export headers is released
specta = { git = "https://github.com/oscartbeaumont/rspc.git" } # TODO: Move back to crates.io release when Specta Ipv4Addr support is released
