[package]
name = "sdcore"
version = "0.1.0"
description = "Virtual distributed filesystem engine that powers Spacedrive."
authors = ["Spacedrive Technology Inc."]
license = "GNU GENERAL PUBLIC LICENSE"
repository = "https://github.com/spacedriveapp/spacedrive"
edition = "2021"

[features]
default = ["ffmpeg"]
ffmpeg = ["ffmpeg-next"]

[dependencies]
p2p = { path = "./p2p" }
core-derive = { path = "./derive" }

# P2P
brotli = "3.3.4"
rmp = "0.8.11"
rmp-serde = "1.1.0"

# Universal Dependencies
base64 = "0.13.0"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4.0", features = ["serde"] }
serde_json = "1.0"
futures = "0.3"
data-encoding = "2.3.2"
ring = "0.17.0-alpha.10"
int-enum = "0.4.0"
hostname = "0.3.1"

# Project dependencies
ts-rs = { version = "6.1", features = ["chrono-impl", "uuid-impl"] }
prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust.git", tag = "0.5.0" }
walkdir = "^2.3.2"
uuid = "0.8"
sysinfo = "0.23.9"
thiserror = "1.0.30"

tokio = { version = "1.17.0", features = ["sync", "rt"] }
include_dir = { version = "0.7.2", features = ["glob"] }
async-trait = "0.1.52"
image = "0.24.1"
webp = "0.2.2"
ffmpeg-next = { version = "5.0.3", optional = true }
fs_extra = "1.2.0"
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.14", features = ["env-filter", "ansi"] }
tracing-appender = "0.2.2"

